name: EasyTravel
main: at.co.hohl.easytravel.TravelPlugin
version: 0.1-snapshot
database: true
authors:
 - 'Michael Hohl (miho)'
commands:
  depart:
    description: Departs, when you inside a travel point.
    usage: /<command> - Departs, when you inside a travel point.
  port:
    description: Manages the TravelPorts of EasyTravel.
    usage: /<command> help - Shows the help of the command.